services:
  typo3:
    image: ghcr.io/mathisburger/devcontainers-typo3-mariadb:latest
    restart: unless-stopped
    environment:
      SERVER_NAME: localhost, php:80
    volumes:
      - ./:/var/www/html
    ports:
      - "8001:80"
      - "9003:9003"  
  db:
    image: mariadb:10.6
    container_name: typo3-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: typo3
      MYSQL_USER: typo3
      MYSQL_PASSWORD: typo3
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"  

volumes:
  db_data:   